//$c1	JT  12/18/00 Created
//========================================================================//
//
//     File Name: sldworks_i.c
//     
//     Application: typelib
//     
//     Contents: Wrapper for the IDL generated header file.
//				 The .c/.h files generated by MIDL of MainWin are 
//               not compatible with the ones generated on NT.
//               [Mainsoft TID: 0200-0010]
//
//========================================================================//

#ifdef MAINWIN
#  include "unix/sldworks_i.c"
#else
#  include "win32/sldworks_i.c"
#endif
