//$c1	JND 10/27/05 Created
//========================================================================//
//              Copyright 2003 (Unpublished Material)                     //
//                  SolidWorks Corp.									  //
//========================================================================//
//
//     File Name: swcommands_i.c
//     
//     Application: typelib
//     
//     Contents: Wrapper for the IDL generated header file.
//				 The .c/.h files generated by MIDL of MainWin are 
//               not compatible with the ones generated on NT.
//               [Mainsoft TID: 0200-0010]
//
//========================================================================//

#ifdef MAINWIN
#  include "unix/swcommands_i.c"
#else
#  include "win32/swcommands_i.c"
#endif
